### PR TITLE
Allow for passing in extra kwargs on Tag creation

### PR DESCRIPTION
**Pull request by rtpg**
When [using custom tags](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html#using-a-custom-tag-or-through-model), you might need to pass in extra keyword arguments when creating new tags through the model manager.

This code change adds the ability to do so, through a `tag_kwargs` argument in the `add` method of the tag managers.

Example usage (if you were using a custom tag model with a `tenant` key, for multi-tenant applications):

```
        document.tags.add("a new tag", tag_kwargs={'tenant': self.tenant})
```

Sending this in as-is for comment, though we have been using these changes in production for quite a long time at this point so at least for our use case it's been valuable.

 If this looks like the kind of thing that y'all want, I can add documentation and tests for this.

### CODE REVIEW

**Comment by PeteAndersen** [comment]
This type of change is definitely needed to make custom tag model usage practical.

**Comment by jdufresne** [comment]
How does this compare to #630? Are these duplicating one another?

**Comment by PeteAndersen** [comment]
`through_defaults` targets extra fields on the intermediate m2m model, while `tag_defaults` would target extra fields on the tag model. I think they're both useful to support.

**Comment by rtpg** [comment]
Alright, thanks for the feedback.  Normally we shouldn't need any more migrations, but we should add some documentation + tests for this. I'll see what I can do here

**Comment by rtpg** [comment]
Sorry for the wait, I've added (meager) documentation and a test for this. I think this is good to go in principle though. @auvipy are there any other changes that you would like to see for this?

**Comment by StriveForBest** [comment]
is it supposed to work? I am getting an error:
```
TypeError: add() got an unexpected keyword argument 'tag_kwargs'
```

**Comment by rtpg** [comment]
@StriveForBest I do not believe there has been a release since this merge, so unless you're installing a specific targetted commit you might not have this change

**Comment by rtpg** [comment]
@StriveForBest we just released a new version of this (`1.3.0`), you should be able to use this feature now

**Pull request merged**
