### PR TITLE
Change deprecated private attribute to support Django>=1.11

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
Hello @jdufresne!

Closes https://github.com/jazzband/django-taggit/issues/624

### CODE REVIEW

**Comment by auvipy** [comment]
thanks

**Comment by jdufresne** [comment]
Thanks @DmytroLitvinov! Is it possible to add a test that exercises this code?

**Comment by DmytroLitvinov** [comment]
@jdufresne I am not sure.
Need to check.

**Comment by jdufresne** [comment]
Thanks, that would be very helpful to avoid future regressions. A good place to start would be to mimic the code path that triggered this bug for you in the first place.

**Pull request merged**
