### PR TITLE
Fix race condition in TaggableManager

### PR DESCRIPTION
**Pull request by mixxorz**
Fixues issue #576 

I'm looking into writing tests for this, but I'm having trouble figuring out how to deterministic-ally test a race condition.

### CODE REVIEW

**Comment by jdufresne** [comment]
This looks like a good change to me, are you able to address the test failures?

**Comment by mixxorz** [comment]
I'm a bit short on time at the moment... I'll eventually get around to it, but I wouldn't mind if you or someone else take a stab at it.

**Comment by mixxorz** [comment]
Thanks man. I really appreciate you fixing the tests. 👍

**Comment by zerolab** [comment]
This is fantastic, thank you!
Is there any chance to have a new release out?

**Comment by jdufresne** [comment]
Thanks for the contribution and testing. I released 0.24.0 today with this fix included.

**Pull request merged**
