### PR TITLE
Fixed #784 -- Added migrations autodetected by Django 4.0

### LINKED ISSUE #784: AUto-generated migration with Django 4.0
Hi,

When using `taggit` with Django 4.0 and running `./manage.py makemigrations`, it generates a new migration file:
```
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
```

I believe this is caused by this: https://docs.djangoproject.com/en/4.0/releases/4.0/#migrations-autodetector-changes

Adding the migration to `taggit` doesn't seem to have negative side-effects. I've also tried adding this migration to taggit locally, reverting Django to 3.2, then running `makemigrations` again and it didn't detect any new changes.

It should be possible to prevent an issue like this from happening again by having `./manage.py makemigrations --check` run as part of your CI.

### PR DESCRIPTION
**Pull request by bmispelon**

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Review by sergeyklay — APPROVED** [review]

**Comment by rtpg** [comment]
Will try to figure out the consequences of this, for libraries we gotta be a bit careful because people are rarely v checking migrations provided by libraries...

**Comment by auvipy** [comment]
will need a new release as well

**Comment by bmispelon** [comment]
> Will try to figure out the consequences of this, for libraries we gotta be a bit careful because people are rarely v checking migrations provided by libraries...

If it helps, [Django's release notes](https://docs.djangoproject.com/en/4.0/releases/4.0/#migrations-autodetector-changes) mentions that the operation are "no-op".

Also, the test I added in the PR should be a strong guarantee that the state of migrations is clean no matter the Django version (I assume tests are run with all supported Django versions).

Let me know if I can be of more help, and thanks everyone for the fast response 👍🏻

**Comment by auvipy** [comment]
merging this for now. any follow up improvements are welcome

**Comment by gasman** [comment]
Happy to report that this was the final blocker in django-taggit towards Django 4.0 support in Wagtail, and with this fix merged we now have Wagtail successfully running under Django 4.0 (https://github.com/wagtail/wagtail/pull/7829). Please consider this a vote of confidence and a nudge for making a new django-taggit release :-)

**Pull request merged**
